import type { Product } from "./types";

export const products: Product[] = [
  {
    id: "p1",
    name: "Noise-Cancelling Headphones",
    description: "Comfortable fit, strong ANC, 30h battery life.",
    price: 12999,
    image: "/images/headphones.png",
    category: "electronics",
    rating: 4.6,
    stock: 10,
  },
  {
    id: "p2",
    name: "Minimal Backpack",
    description: "Water-resistant, laptop compartment, durable zips.",
    price: 4999,
    image: "/images/backpack.png",
    category: "fashion",
    rating: 4.3,
    stock: 18,
  },
  {
    id: "p3",
    name: "Ergonomic Desk Lamp",
    description: "Warm light, adjustable arm, minimal footprint.",
    price: 2599,
    image: "/images/lamp.png",
    category: "home",
    rating: 4.2,
    stock: 12,
  },
  {
    id: "p4",
    name: "Bestselling Novel",
    description: "A page-turner you won’t put down.",
    price: 899,
    image: "/images/book.png",
    category: "books",
    rating: 4.7,
    stock: 40,
  },
  // Add 4–8 more products similarly
  // Add these inside your products: Product[] = [ ... ] array

{
  id: "p5",
  name: "Wireless Mouse",
  description: "Ergonomic wireless mouse with silent clicks and 2.4GHz dongle.",
  price: 1499,
  image: "/images/mouse.png",
  category: "electronics",
  rating: 4.4,
  stock: 25,
},
{
  id: "p6",
  name: "Mechanical Keyboard",
  description: "Compact mechanical keyboard with tactile switches and white backlight.",
  price: 3499,
  image: "/images/keyboard.png",
  category: "electronics",
  rating: 4.6,
  stock: 12,
},
{
  id: "p7",
  name: "Stainless Steel Water Bottle",
  description: "Double-wall insulated bottle that keeps drinks cold/hot for hours.",
  price: 999,
  image: "/images/bottle.png",
  category: "home",
  rating: 4.3,
  stock: 40,
},
{
  id: "p8",
  name: "Ceramic Coffee Mug",
  description: "Minimal ceramic mug with comfortable handle. Microwave safe.",
  price: 599,
  image: "/images/mug.png",
  category: "home",
  rating: 4.2,
  stock: 30,
},
{
  id: "p9",
  name: "Cotton T-Shirt",
  description: "Soft, breathable cotton tee with a clean fit for everyday wear.",
  price: 799,
  image: "/images/tshirt.png",
  category: "fashion",
  rating: 4.1,
  stock: 50,
},
{
  id: "p10",
  name: "Running Shoes",
  description: "Lightweight shoes with cushioned sole and good grip for daily runs.",
  price: 2999,
  image: "/images/shoes.png",
  category: "fashion",
  rating: 4.5,
  stock: 16,
},
{
  id: "p11",
  name: "Personal Finance Handbook",
  description: "Simple guide to budgeting, saving, and investing for beginners.",
  price: 499,
  image: "/images/finance-book.png",
  category: "books",
  rating: 4.6,
  stock: 35,
},
{
  id: "p12",
  name: "Productivity Planner",
  description: "Undated weekly planner with goal setting and habit tracking pages.",
  price: 699,
  image: "/images/planner.png",
  category: "books",
  rating: 4.4,
  stock: 22,
},
];